### ISSUE TITLE
You should remove this line or make you repo private

### ISSUE THREAD

**Issue by MatthewGrant** [Aldaviva/DadsEnergyReporter#7]
https://github.com/Aldaviva/DadsEnergyReporter/blob/a23f62ef6bf17d0ec588e6889d267cbff8412822/Tests/Remote/OrangeRockland/Client/OrangeRocklandAuthenticationClientTest.cs#L71

**Comment by Aldaviva** [comment]
The comment edit history preserves the old file hash, so I'm going to delete this comment to remove that reference. Rest assured I appreciate your disclosure and I'm not trying to cover up the fact that you helped me. Thanks again.
